### PR TITLE
Mc button

### PR DESCRIPTION
**Pull request by MCaldwell-42**
*button has two styles (light and dark) in the button.scss however I'm not a pro styler so they may still need sprucing up.  Both examples are on display in index right now. 
*It is also set up dynamically so that variation in wording on the buttons should still go to the right place. (example: Buy Tickets button will take one to the ticket page, but a button that only says Tickets will still do the same thing)

#23

### CODE REVIEW

**Comment by Hellrungj** [comment]
Good so far. Need to work on the following:
- [x] button spacing
- [x] button outline
- [x] button colors
- [x] button text font

Let @lapinell, @lnbailey or myself know if you need any help with styling.

**Comment by MCaldwell-42** [comment]
Ok, I've adjusted both the btn-light and btn-dark button styles to something much closer to the mock up. Also realized that I had an extra dash in both classes so that neither were properly targeting the buttons when we reviewed it yesterday lol.  
Please let me know when you've had time to review it again. Thanks.

**Review by Hellrungj — APPROVED** [review]
That buttons look great and they function great. Thanks. 👍

**Comment by Hellrungj** [comment]
Merging this branch into the main.

**Pull request merged**
